### ISSUE TITLE
node-gyp rebuild failed

### ISSUE THREAD

**Issue by vallerydelexy** [mukundsolanki/syncpad-server#1]
node-gyp rebuild       
gyp info it worked if it ends with ok
gyp info using node-gyp@10.2.0
gyp info using node@18.19.1 | darwin | arm64
gyp info find Python using Python version 3.9.6 found at "/Applications/Xcode.app/Contents/Developer/usr/bin/python3"

gyp info spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3
gyp info spawn args [
gyp info spawn args '/Users/rizki.aprita/.bun/install/global/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'make',
gyp info spawn args '-I',
gyp info spawn args '/Users/rizki.aprita/Documents/projects/syncpad-server/build/build/config.gypi',
gyp info spawn args '-I',
gyp info spawn args '/Users/rizki.aprita/Documents/projects/syncpad-server/build/config.gypi',
gyp info spawn args '-I',
gyp info spawn args '/Users/rizki.aprita/.bun/install/global/node_modules/node-gyp/addon.gypi',
gyp info spawn args '-I',
gyp info spawn args '/Users/rizki.aprita/Library/Caches/node-gyp/18.19.1/include/node/common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=/Users/rizki.aprita/Library/Caches/node-gyp/18.19.1',
gyp info spawn args '-Dnode_gyp_dir=/Users/rizki.aprita/.bun/install/global/node_modules/node-gyp',
gyp info spawn args '-Dnode_lib_file=/Users/rizki.aprita/Library/Caches/node-gyp/18.19.1/<(target_arch)/node.lib',
gyp info spawn args '-Dmodule_root_dir=/Users/rizki.aprita/Documents/projects/syncpad-server/build',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp: binding.gyp not found (cwd: /Users/rizki.aprita/Documents/projects/syncpad-server/build) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack at ChildProcess.<anonymous> (/Users/rizki.aprita/.bun/install/global/node_modules/node-gyp/lib/configure.js:317:18)
gyp ERR! stack at ChildProcess.emit (node:events:517:28)
gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:292:12)
gyp ERR! System Darwin 24.0.0
gyp ERR! command "/Users/rizki.aprita/.nvm/versions/node/v18.19.1/bin/node" "/Users/rizki.aprita/.bun/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/rizki.aprita/Documents/projects/syncpad-server/build
gyp ERR! node -v v18.19.1
gyp ERR! node-gyp -v v10.2.0
gyp ERR! not ok

**Comment by mukundsolanki** [comment]
On which platform are you trying to run?

**Comment by th3cr0wd** [comment]
I got a very similar error on windows.
gyp: binding.gyp not found (cwd: C:\syncpad-server) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack at ChildProcess.<anonymous> (C:\Users\Honza\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:317:18)
gyp ERR! stack at ChildProcess.emit (node:events:519:28)
gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:294:12)
gyp ERR! System Windows_NT 10.0.22631
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Honza\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\syncpad-server
gyp ERR! node -v v20.17.0
gyp ERR! node-gyp -v v10.2.0
gyp ERR! not ok
